import Head from 'next/head'
import { Inter } from 'next/font/google'
import ScrollTrigger from 'react-scroll-trigger';
import { useCallback, useState } from 'react';
import Header from '@/components/header';
import Slider from '@/components/slider';
import WhyChouseUs from '@/components/whyChouseUs';
import Swap from '@/components/swap';
import Tokenomic from '@/components/tokenomic';
import About from '@/components/about';
import Desc from '@/components/desc';
import Footer from '@/components/footer';
import ContactUs from '@/components/contactUs';
import copy from 'clipboard-copy';
import { toast } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const text = "0x220c8466E939AF4a07969fcD440Eb9f5C799c528"
  const handleCopy = useCallback(() => {
    copy(text);
    toast.success("Copied")
  }, [text]);
  return (
    <>
      <Head>
        <title>HAJI INU</title>
        <meta name="description" content="Generated by HAJI INU" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={`${inter.className}`}>
        <Header/>
        <Slider/>

        <h5 onClick={handleCopy} style={{background: "#5b0279" , cursor:"pointer"}} className='address_text m-0 w-100 py-3 text-center'>
            Address :<br/> {text}
        </h5>
        <Swap/>

      
        <WhyChouseUs/>
        <Tokenomic/>
        <About/>
        <Desc/>
        <ContactUs/>
        <Footer/>
     
      </div>
    </>
  )
}
